-- require('dressing').setup({
--   input = {
--     -- enabled = false,
--     -- use defaults
--     relative = 'editor',
--   },
--   select = {
--     telescope = require('telescope.themes').get_cursor(),
--   },
-- })
