local ui = require('harpoon.ui')

nmap('<leader>m', require('harpoon.mark').add_file)
nmap('<leader>hh', ui.toggle_quick_menu)

nmap('<leader>1', function()
  ui.nav_file(1)
end)
nmap('<leader>2', function()
  ui.nav_file(2)
end)
nmap('<leader>3', function()
  ui.nav_file(3)
end)
nmap('<leader>4', function()
  ui.nav_file(4)
end)
