local km = require('core.keymaps')
local opts = { silent = true }

km.nnoremap('<leader>m', function()
  require('harpoon.mark').add_file()
end, opts)
km.nnoremap('<leader>h', function()
  require('harpoon.ui').toggle_quick_menu()
end, opts)

km.nnoremap('<leader>j', function()
  require('harpoon.ui').nav_file(1)
end, opts)
km.nnoremap('<leader>k', function()
  require('harpoon.ui').nav_file(2)
end, opts)
km.nnoremap('<leader>l', function()
  require('harpoon.ui').nav_file(3)
end, opts)
km.nnoremap('<leader>;', function()
  require('harpoon.ui').nav_file(4)
end, opts)
